- name: Install Nagios 4.4.5 on Red Hat Enterprise Linux 8.2
  hosts: all
  tasks:
    - name: Import the EPEL cryptographic signature
      rpm_key:
        key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        state: present

    - name: Ensure the EPEL repo is enabled
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present

    - name: Install Nagios server
      yum:
        name: mod_ssl, git, httpd, mariadb-server, php-mysqlnd, php-fpm, nagios, nagios-selinux, nagios-common, nagios-plugins, lsof, gcc, glibc, glibc-common, wget, gd, gd-devel, perl, postfix
        state: present

    - name: Start and enable Nagios services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - mariadb
        - nagios

    - name: Make Nagios use SSL
      replace:
        path: /etc/nagios/cgi.cfg
        regexp: 'use_ssl_authentication=0'
        replace: 'use_ssl_authentication=1'
      register: nagios_set_ssl

    - name: Restart Nagios if we made a config change for SSL
      service:
        name: nagios
        state: restarted
      when: nagios_set_ssl.changed
