- name: Install Nagios on Red Hat Enterprise Linux 8.2
  hosts: all
  tasks:
    - name: Import the EPEL cryptographic signature
      rpm_key:
        key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        state: present

    - name: Ensure the EPEL repo is enabled
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present

    - name: Enable CentOS 8 PowerTools repo needed for some perl tools
      yum_repository:
        name: PowerTools
        description: CentOS 8 PowerTools
        mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra
        enabled: yes
        gpgcheck: no

    - name: Install Nagios server
      yum:
        name: jq, dnf-plugins-core, mod_ssl, git, httpd, mariadb-server, php-mysqlnd, php-fpm, nagios, nagios-selinux, nagios-common, nagios-plugins, lsof, gcc, glibc, glibc-common, wget, gd, gd-devel, perl, postfix
        state: present

    - name: Start and enable Nagios services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - mariadb
        - nagios

    - name: Configure Nagios server to use SSL
      replace:
        path: /etc/nagios/cgi.cfg
        regexp: 'use_ssl_authentication=0'
        replace: 'use_ssl_authentication=1'
      register: nagios_set_ssl

    - name: Configure Nagios to disable auth DEMO ONLY
      replace:
        path: /etc/nagios/cgi.cfg
        regexp: 'use_authentication=1'
        replace: 'use_authentication=0'
      register: nagios_use_auth

    - name: Restart Nagios if config done
      service:
        name: nagios
        state: restarted
      when: nagios_set_ssl.changed or nagios_use_auth.changed
