---
- name: Check if a Window server is alive
  hosts: all
  tasks:
  - name: Log into the server and check that the ping modules returns output
    ansible.windows.win_ping:
      data: win-pong from Ansible
