- name: New group in Windows
  hosts: all
  tasks:
  - name: Create a new group
    ansible.windows.win_group:
      name: "{{ group_name }}"
      description: "{{ group_desc }}"
      state: present
